version: 2.1
orbs:
  ship: auth0/ship@0.7.7
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "examples/kitchen-sink-example/package.json" }}
      - run: npm ci
      - run:
          name: npm run install:kitchen-sink
          command: |
            if [ -z "$CIRCLE_PR_NUMBER" ]; then
              npm run install:kitchen-sink
            fi
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum "examples/kitchen-sink-example/package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run build
      - run: npm test
      - run: npm run lint
      - run:
          name: browserstack
          command: |
            if [ -z "$CIRCLE_PR_NUMBER" ]; then
              npx start-server-and-test 'start:kitchen-sink-local' http://localhost:3000 'browserstack-cypress run --build-name $CIRCLE_BRANCH --no-wrap'
            fi
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
workflows:
  Build and Test:
    jobs:
      - build:
          context:
            - browserstack-env
      - ship/node-publish:
          requires:
            - build
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - main
